KNOWN_STORES = {
    "BON PREU": ["BON PREU", "BONPREU", "BON-PREU"],
    "ESCLAT": ["ESCLAT", "ESCIAT"],
    "MERCADONA": ["MERCADONA"],
    "CARREFOUR": ["CARREFOUR"],
    "DIA": ["DIA %", "DIA MARKET"],
    "LIDL": ["LIDL"],
    "ALDI": ["ALDI"],
    "MEDIA MARKT": ["MEDIA MARKT", "MEDIAMARKT", "MEDIA MARKT SATURN"],
}

PRODUCT_HEADER_KEYWORDS = [
    "DESCRIP",
    "PRODUCTO",
    "CANT.",
    "P.V.P",
    "PVP",
    "UNITARIO",
    "TRIBUTARIA",
    "POR UNIDAD",
    "BASE IMPONIBLE",
    "CUOTA IVA",
    "TIPO IVA",
    "FACTURA",
    "P.UNIT",
]

DISCARDED_LINE_KEYWORDS = [
    "DESCUENTO",
    "CUPON",
    "CUPÓN",
    "LOY_",
    "APP",
    "GASTOS",
    "ENVIO",
    "ENVÍO",
]

PAYMENT_SECTION_KEYWORDS = [
    "TARGETA BANCARIA",
    "TARJETA BANCARIA",
    "TARGETA",
    "TARJETA",
    "TARG. BANCARIA",
    "TARG BANCARIA",
    "TARGETA BANCÀRIA",
    "TARJETA BANCÀRIA",
    "EFECTIU",
    "EFECTIVO",
    "CANVI:",
    "CAMBIO:",
    "VERIFICAT PER",
    "VERIFICADO POR",
    "VISA DEBIT",
    "VISA CREDIT",
    "MASTERCARD",
    "MAESTRO",
    "AID:",
    "AID ",
]

ADDRESS_HINT_KEYWORDS = [
    "TELÈFON",
    "TELEFON",
    "TELÉFONO",
    "TEL.",
    "RONDA DE ",
    "CARRER ",
    "AVINGUDA ",
    "PASSEIG ",
    "PLAÇA ",
    "CALLE ",
    "AVDA.",
    "PLAZA ",
    "C/ ",
]

NON_PRODUCT_HINTS = [
    "TOTAL",
    "TARGETES",
    " CANVI",
    "CANVI:",
    "DESGLOSSAMENT",
    "DESGLOSAMENT",
    "DESGLOSSPMENT",
    "D'IVA",
    "ARTICLES",
    "IVA",
    "BASE IMPOSABLE",
    "DATA",
    "FECHA",
    "HORA",
    "TICKET",
    "NIF",
    "BON PREU",
    "ESCLAT",
    "MERCADONA",
    "CARREFOUR",
    "LIDL",
    "ALDI",
    "DIA",
    "GRACIES",
    "GRÀCIES",
    "FACTURA",
    "CLIENTE",
    "DIRECCION",
    "PAGO",
    "CUPON",
    "CUPÓN",
    "DESCUENTO",
    "ENVIO",
    "GASTOS",
    "TIPO IVA",
    "BASE IMPONIBLE",
    "CUOTA IVA",
    "TRIBUTARIA",
    "POR UNIDAD",
    "UNITARIO",
    "UNIDAD",
    "MEDIA MARKT",
    "SATURN",
    "UNIPERSONAL",
    "REGISTRO",
    "MERCANTIL",
    "PAGINA",
    "PEDIDO",
    "REFERENCIA",
    "METODO",
    "NUMERO",
    "IDENTIFICACION",
    "RECOGIDA",
    "TIENDA",
    "ENTREGA",
    "TELEFONO",
    "TELÉFONO",
    "TELÈFON",
    "EMAIL",
    "REEMPLAZA",
    "LOY_",
    "APP",
    "CAIXERA",
    "CAIXA",
    "ATES PER",
    "ATESA PER",
    "TARGETA",
    "TARJETA",
    "BANCARIA",
    "BANCÀRIA",
    "VERIFICAT",
    "DISPOSITIU",
    "VISA",
    "DEBIT",
    "MASTERCARD",
    "MAESTRO",
    "EFECTIU",
    "EFECTIVO",
    "QUOTA",
    "AID:",
    "RONDA DE ",
    "CARRER ",
    "AVINGUDA",
    "PASSEIG",
    "PLAÇA",
    "P.UNIT",
    "OP:",
]
